export default {
	colors: {

		PRIMARY: "#ADDDFF",
		SECONDARY: "#1F8FFF",

		BACKGROUND_PRIMARY: "#FAFAFA",
		BACKGROUND_SECONDARY: "#F1F1F1",
		BACKGROUND_THIRD: "#DEDEDE",

		FONT_COLOR_PRIMARY: "#2B2F33",
		FONT_COLOR_SECONDARY: "#FAFAFA",
		FONT_COLOR_THIRD: "#4F6780",

		INPUT_BORDER: "#D4D4D4",

		ALERT: "#FF4D4D",
	}
};

